### ISSUE TITLE
Utilize official LSP?

### ISSUE THREAD

**Issue by codefriar** [nawforce/apex-link#28]
Evening Kevin,

I was just curious, looking at how you're writing this and generating an atnlr etc... 

Why not integrate and use the official LSP?

**Comment by nawforce** [comment]
Really just simply because it's not open source, well really the jorje JAR isn't which is the most interesting bit for me. I did at one point consider swapping to use it but I had done most the parsing work by that point so I would just be losing flexibility. 

The parsing itself is not really the hard part of the project, it's working out how the runtime uses the parsed code, things like how types are discovered without imports or how function matching works. As you are probably aware a lot of this type of thing only has cursory documentation, so I have had to reverse a lot of behaviours to get to this point.

**Comment by codefriar** [comment]
@nawforce would it be beneficial to have a public version of the official antlr file? - no promises, but I'm having a conversation.

**Comment by nawforce** [comment]
Got to be a good thing for getting consistent tooling IMO, even if I might be a bit past needing it myself. There has been some discussion on if this might be possible in past that Nate Totten & Chris Peterson can help fill in details on.
