### ISSUE TITLE
Ability to exclude/remove nodes from the dependency explorer.

### ISSUE THREAD

**Issue by FishOfPrey** [nawforce/apex-link#29]
My project has a number of classes the are almost universally referenced. Classes that handle DML for security (ESAPI.cls) . A common exception handling class. Constants. 

These few classes and their corresponding dependencies can make the dependency graph really hard to untangle as just about everything links to one or more of them.

Would it be possible to drop them and their isolated dependencies from the graph? 

Maybe an option to drop a node from the current graph, or a blocklist for classes that you know you won't want to see.

**Comment by nawforce** [comment]
Good idea, I have same issue with fflib_*. I guess the nice VSCode way to do this would be to add a setting for exclusions so you can check them in and then allow dynamic exclusions as well so you can further trim if things get a bit messy?

**Comment by nawforce** [comment]
Done part of this, there is a setting you can set with an exclusion regex. It works on the name of classes rather than paths, but that makes it a bit easier I think as that is what the dependency explorer is showing. This is in version 1.1.0. I have a few revisions to make to the explorer itself so I will look at adding a why to do this dynamically as well.

![Screenshot 2021-03-07 at 22 18 30](https://user-images.githubusercontent.com/25647167/110256863-1722aa80-7f93-11eb-840f-9a6fffd58338.png)
