### ISSUE TITLE
Is your retest code still available?

### ISSUE THREAD

**Issue by jclark-dot-org** [nawforce/apex-link#80]
Came here via [your blog post][1], via [your SFSE answer on parallel testing][2], to have a look at your apexlink:retest code as I need to support a large codebase I'm not familiar with, and I'd like to speed up testing times.  Looks like you've factored it out of this package, but I didn't spot it in a quick pass through your public repos.  Is it still available to review?

[1]: https://nawforce.wordpress.com/2019/06/09/parallel-unit-testing-via-sfdx-cli/
[2]: https://salesforce.stackexchange.com/a/265066/149

**Comment by nawforce** [comment]
Hi Jason, Sorry for the delay getting back to you on this. I have moved things around a bit since and removed it but you can see at https://github.com/nawforce/apex-link/blob/v0.4.0/cli/src/commands/apexlink/retest.ts.

One thing that was discovered later was that sometimes when you ask the platform to run all test, it does not, so really you need to track the tests you expect to run against what actually does run. This testing approach was also implemented in CumulusCI, I have not used that implementation but they also ran into the same problem, https://s'alesforce.stackexchange.com/questions/262893/any-way-to-get-consistent-test-counts-when-parallel-testing-is-used.'

**Comment by jclark-dot-org** [comment]
Thanks Kevin, this will be very useful - and the linked info on "connection was cancelled here" errors was quite interesting.  The linked Known Issue is reported fixed, so I guess the completion count issue may be resolved but I'm certain the underlying "cancelled here" issue isn't; that was a constant issue in the last large test code base I tried to parallelize. 

Closed with my thanks
